version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "erri120"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
